### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by ErikvdVen** [albertjuhe/charikars_algorithm#1]
After running `java -jar dedup.jar ../test/text_sample_2.txt ../test/text_sample_1.txt  max 3 min 3` I get this error: 

`Near-duplicates detector UOC. v2.5
Charika simhash, with hashRabin and Hamming distance.
Token ngrams 3-3.
Exception in thread "main" java.lang.NullPointerException
    at net.olivo.lc4j.LanguageCategorization.loadLanguages(LanguageCategorization.java:321)
    at edu.uoc.myway.language.LanguageDetector.<init>(LanguageDetector.java:20)
    at uoc.dedup.document.fingerprintDocument.detectLanguage(fingerprintDocument.java:72)
    at uoc.dedup.document.fingerprintDocument.<init>(fingerprintDocument.java:53)
    at uoc.dedup.document.fingerprintCharikar.<init>(fingerprintCharikar.java:59)
    at duplicador.Main.main(Main.java:98)`

Any thoughts?

**Comment by albertjuhe** [comment]
Hi Erik,

This could happend because the algorithm can't find the language models to
determine in which language are written the files, the net.olivo.lc4j is a
library designed to detect in which language has been written a text, to do
this stuff the lib needs a language models generated previously, this
models are stored in the folder resources/models/*.lm.

in this class edu.uoc.myway.language

private String languagesModelsDirPath = "resources\models"; <- this is the
path where to find the language models, this must be an external and
configurable variable and not a hard coded variable I will correct.

 public LanguageDetector() {
        lc = new LanguageCategorization();
        try {
            lc.loadLanguages(languagesModelsDirPath); <-- Here is where the
error is triggered
        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage() + "- No s'ha trobat el
directori: " + languagesModelsDirPath);
        } catch (IOException e) {
            System.out.println(e.getMessage() + " - Error de lectura del
directori: " + languagesModelsDirPath);
        }
    }

try changing the path or storing the resource folder in the same folder
than the dedup.jar.

2015-05-11 10:52 GMT+02:00 Erik van de Ven notifications@github.com:

**Comment by ErikvdVen** [comment]
Alright, thank you very much for your quick response! I will try changing the path!

**Comment by ErikvdVen** [comment]
Alright, changing the path worked!

**Comment by albertjuhe** [comment]
Great!!!

2015-05-11 13:13 GMT+02:00 Erik van de Ven notifications@github.com:
